services:
  kkk-postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  kkk-nginx:
    image: nginx:1.25
    container_name: kkk-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./../src:/var/www/html/
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./logs:/var/log/nginx/
      - ./ssl:/var/ssl/
    depends_on:
      - kkk-php
      - kkk-ssl
  kkk-php:
    container_name: kkk-php
    build: ./php
    ports:
      - '9000:9000'
      - '9003:9003'
    volumes:
      - ./../src:/var/www/html/
    depends_on:
      - kkk-postgres
  kkk-ssl:
    build: ./ssl
    volumes:
      - ./ssl:/ssl/