<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250504161040 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

        $this->addSql(<<<'SQL'
            ALTER TABLE api_key ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE api_key ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE log ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE log ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN log.created_at IS ''
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE photo ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE photo ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position_group ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position_group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER requested_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN reset_password_request.requested_at IS ''
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN reset_password_request.expires_at IS ''
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE season ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE season ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE settings ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE settings ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tag ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tag ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE timer ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE timer ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE tag ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE tag ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE settings ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE settings ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE photo ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE photo ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER requested_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reset_password_request ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN reset_password_request.requested_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN reset_password_request.expires_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE api_key ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE api_key ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE timer ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE timer ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE season ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE season ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ingredient ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "user" ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position_group ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position_group ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE log ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE log ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE log ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            COMMENT ON COLUMN log.created_at IS '(DC2Type:datetime_immutable)'
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_position ALTER id DROP IDENTITY
        SQL);
    }
}
